begin;

-- Future AI copy was generated by the old site-heavy rotation. Retire only
-- unpublished scheduled items so the generator can refill those slots with
-- the new balanced topic plan. Published and manual content remains intact.
update public.content_queue
set status = 'failed',
    generation_key = null,
    next_retry_at = null,
    processing_started_at = null,
    last_error = 'Retired after content topic rotation update'
where origin = 'ai_generated'
  and status = 'scheduled'
  and scheduled_at > now();

commit;
